name: Deploy via Tailscale

on:
  # Se activa cada vez que haces un 'git push' a cualquier ramassss
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Instala Tailscale en el runner de GitHub
      - name: Install Tailscale
        run: curl -fsSL https://tailscale.com/install.sh | sh

      # 2. Conecta el runner a tu red de Tailscale
      - name: Connect to Tailscale
        run: sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=github-runner

      # 3. Configura la clave SSH privada para la conexión
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 4. Se conecta a tu servidor y ejecuta el script de despliegue
      - name: Deploy to Server
        run: |
          # Guarda el nombre de la rama actual en una variable
          BRANCH_NAME=${{ github.ref_name }}
          # Ejecuta el script en el servidor, pasándole el nombre de la rama
          ssh -o StrictHostKeyChecking=no adso@100.69.132.91 "/var/www/deploy.sh $BRANCH_NAME"
