name: Deploy via Tailscale

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Instalar Tailscale
      - name: Install Tailscale
        run: curl -fsSL https://tailscale.com/install.sh | sh

      # 2️⃣ Conectar el runner a Tailscale
      - name: Connect to Tailscale
        run: sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=github-runner

      # 3️⃣ Esperar hasta que el servidor remoto sea reachable
      - name: Wait for Tailscale connection
        run: |
          SERVER_IP="100.123.209.103"
          echo "Esperando que $SERVER_IP responda..."
          until tailscale ping $SERVER_IP; do
            echo "Esperando Tailscale..."
            sleep 5
          done
          echo "$SERVER_IP está reachable"
          tailscale status

      # 4️⃣ Configurar clave SSH
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 100.123.209.103 >> ~/.ssh/known_hosts

      # 5️⃣ Ejecutar deploy en el servidor remoto
      - name: Deploy to Server
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          ssh -o StrictHostKeyChecking=yes adso@100.123.209.103 "/var/www/deploy.sh $BRANCH_NAME"
