name: Deploy via Tailscales

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Instalar Tailscale
      - name: Install Tailscale
        run: curl -fsSL https://tailscale.com/install.sh | sh

      # 2️⃣ Conectar el runner a Tailscale
      - name: Connect to Tailscale
        run: sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=github-runner

      # 3️⃣ Esperar que Tailscale esté listo (sin ping)
      - name: Wait for Tailscale connection
        run: |
          echo "Esperando conexión a Tailscale..."
          sleep 20
          tailscale status

      # 4️⃣ Configurar clave SSH
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 5️⃣ Probar SSH antes del deploy
      - name: Test SSH connection
        run: |
          echo "Probando conexión SSH..."
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 adso@100.123.209.103 "echo 'SSH funciona desde GitHub Actions'"

      # 6️⃣ Ejecutar deploy
      - name: Deploy to Server
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 adso@100.123.209.103 "/var/www/deploy.sh $BRANCH_NAME"