name: Deploy via Tailscale

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tailscale
        run: curl -fsSL https://tailscale.com/install.sh | sh

      - name: Connect to Tailscale
        run: sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=github-runner

      - name: Wait for Tailscale connection
        run: |
          echo "Esperando conexión a Tailscale..."
          sleep 20
          tailscale status
          echo "Mi IP de Tailscale:"
          tailscale ip

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Server
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 adso@100.123.209.103 "/var/www/deploy.sh $BRANCH_NAME"