name: Deploy via Tailscale

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via HTTP webhook
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          echo "🚀 Desplegando rama: $BRANCH_NAME"
          
          response=$(curl -s -X POST "https://adso.tail48df19.ts.net/webhook/deploy" \
            -H "Content-Type: application/json" \
            -d "{\"branch\": \"$BRANCH_NAME\"}" \
            --max-time 300 \
            -w "HTTP_CODE:%{http_code}")
          
          echo "📡 Respuesta: $response"
          
          if echo "$response" | grep -q "HTTP_CODE:200"; then
            echo "✅ Deploy exitoso"
          else
            echo "❌ Deploy falló"
            exit 1
          fi