name: Deploy via Tailscale

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Instala Tailscale en el runner de GitHub
      - name: Install Tailscale
        run: curl -fsSL https://tailscale.com/install.sh | sh

      # 2. Conecta el runner a tu red de Tailscale
      - name: Connect to Tailscale
        run: sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=github-runner

      # 3. Esperar y verificar conexión
      - name: Wait for Tailscale connection
        run: |
          echo "Esperando conexión a Tailscale..."
          sleep 15
          tailscale status
          ping -c 3 100.123.209.103

      # 4. Configura la clave SSH privada
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 5. Se conecta a tu servidor y ejecuta el script
      - name: Deploy to Server
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          ssh -o StrictHostKeyChecking=no adso@100.123.209.103 "/var/www/deploy.sh $BRANCH_NAME"